language: python
install:
  - pip install -r ogreserver/config/requirements.txt --pre
  - pip install -r requirements_test.txt
  - cd ogreclient && python setup.py install && cd ..
python:
  - '2.7'
before_script:
  - curl http://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
  - echo "deb http://download.rethinkdb.com/apt precise main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get -q update
  - sudo apt-get install rethinkdb=1.13.3-0ubuntu1~precise
  - sudo touch /etc/rethinkdb/instances.d/default.conf
  - sudo service rethinkdb restart
  - mysqladmin -u root password 'eggs'
script:
  - py.test -m 'not requires_calibre'
branches:
  only:
    - master
    - develop
git:
  submodules: false
env:
  - TRAVIS_CI=true
after_success:
  - coveralls
