# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "jessie-2015.8.3"
  #config.vm.box = "mafrosis/jessie64-gb-salt"
  #config.vm.box_version = "2015.5.x.2"
  #config.vm.box_version = "2015.8.x.1"
  config.vm.provider :vmware_fusion do |v|
    v.vmx['memsize'] = 1024
    v.vmx['numvcpus'] = 2
  end

  # create a shared dir in /tmp
  config.vm.synced_folder "/tmp", "/tmp/host_machine"

  # use local development version of salt-formulae
  config.vm.synced_folder "/Users/mafro/Development/salt-formulae", "/srv/salt-formulae"

  config.vm.synced_folder "../..", "/srv/salt"

  config.vm.provision :salt do |salt|
    salt.minion_config = "salt-minion.conf"
    salt.run_highstate = false
    salt.bootstrap_options = "-F -c /tmp"
  end
end
